# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/drivers/memory/mediatek/

obj-$(CONFIG_MEDIATEK_DRAMC)	+= dramc.o
obj-$(CONFIG_MEDIATEK_EMI)	+= emicen.o
obj-$(CONFIG_MEDIATEK_EMI)	+= emimpu.o
obj-$(CONFIG_MEDIATEK_EMI)	+= emibwm.o
